on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "FlightControl-Master/MOOSE_INCLUDE"
          source_branch: "main"
          destination_repo: "nicelym/MM_MOOSE_INCLUDE"
          destination_branch: "main"
