name: Sync with upstream
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch upstream changes
        run: git fetch upstream
      - name: Merge upstream changes
        run: git merge upstream/main --no-edit
      - name: Push changes to origin
        run: git push origin main
